name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run tests
      run: npm test
      
    - name: Test CLI basic functionality
      run: |
        set +e
        output=$(node src/index.js 2>&1)
        exit_code=$?
        echo "CLI output: $output"
        echo "Exit code: $exit_code"
        if echo "$output" | grep -q "Usage:"; then
          echo "✅ CLI test passed - found Usage message"
          exit 0
        else
          echo "❌ CLI test failed - Usage message not found"
          exit 1
        fi

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build binaries
      run: npm run build:pkg
    
    - name: Test Linux binary
      run: ./dist/linux/iswith 2>&1 | grep -q "Usage:"
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: dist/
        retention-days: 30