name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build binaries
      run: npm run build:pkg
    
    - name: Create release archives
      run: |
        cd dist
        tar -czf iswith-linux-x64.tar.gz -C linux iswith
        tar -czf iswith-macos-x64.tar.gz -C macos iswith
        zip -j iswith-windows-x64.zip windows/iswith.exe
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/iswith-linux-x64.tar.gz
          dist/iswith-macos-x64.tar.gz
          dist/iswith-windows-x64.zip
        generate_release_notes: true
        draft: false
        prerelease: false